# -*- coding: utf-8 -*-
"""Untitled33.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10HxrY05bzWsYq8-3TRHKIXrPoe2aktTD
"""
import os
os.chdir(r"C:\Users\Abhishek.S\Desktop\Analysis")
#import time as t
#%%
import requests
def find_address(latlong):
  key="AIzaSyAVv5ZvaIZ1S4od-VMPmQHc-1kgtL01bOM"
  post="https://maps.googleapis.com/maps/api/geocode/json?latlng="
  url =post+str(latlong[0])+","+str(latlong[1])+"&key="+key
  #print(url)
  #t.sleep(0.5)
  r = requests.get(url = url)
  d = r.json()
  address=d["results"][0]["formatted_address"]
  a=d["results"][0]["address_components"]
  post_code="not_found"
  for i in a:
    #print(i["types"])
    if (i["types"][0]=="postal_code"):
      
      post_code=i["long_name"]
    
  #print(address,post_code)
 
  return address,post_code

import pandas as pd
df = pd.read_csv("latlong.csv")
la=df["Lat"]
lo=df["Long"]
latlong=[[la[i], lo[i]] for i in range(0, len(la))]
add_lis=[]
post_lis=[]
j = 0
for i in latlong:
    print(j+1)
    address,post_code=find_address(i)
    add_lis.append(address)
    post_lis.append(post_code)
    j=j+1
df["ADDRESS"]=add_lis
df["PINCODE"]=post_lis
df.to_csv('latlong_output.csv',index = False, encoding = 'utf-8')



